### ISSUE TITLE
Would this project allow eventually FreeDOS to boot on UEFI without a CSM?

### ISSUE THREAD

**Issue by volkertb** [tkchia/biefircate#1]
Hi @tkchia,

Interesting project. Since its aim is to "_run x86-16 or x86-32 code from an x86-64 UEFI environment_", am I correct in assuming that this would be a piece of the puzzle towards getting FreeDOS to boot on modern (64-bit) UEFI systems, even on those lacking a CSM?

In addition to biefircate, what else would be necessary for that? Could biefircate also provide Int 10h and Int 13h thunks, to provide FreeDOS (and real mode DOS apps) access to graphics and disk routines in 64-bit UEFI?

Or putting it differently, could biefircate more or less be considered a generic CSM for modern systems lacking it?

Going a step further, could biefircate eventually also be extended to function as a hardware-assisted hypervisor that could emulate some legacy hardware such as legacy VGA and Sound Blaster, while allowing direct pass-through access to other hardware?

With something like this, native FreeDOS support could be extended even to newer post-CSM PCs, as long as x86 CPUs still have native 86-16 and x86-32 support, even if only inside a hardware-assisted VM instance.

Great work, regardless!

**Comment by tkchia** [comment]
Hello @volkertb,

> am I correct in assuming that this would be a piece of the puzzle towards getting FreeDOS to boot on modern (64-bit) UEFI systems, even on those lacking a CSM?

Yes.  That is the (kind of) big fluffy goal, anyway.

> Could biefircate also provide Int 10h and Int 13h thunks, to provide FreeDOS (and real mode DOS apps) access to graphics and disk routines in 64-bit UEFI?

Well, yes, the [general aim](https://github.com/tkchia/biefircate/blob/main/NOTES.asciidoc) is to implement at least the BIOS interrupts, including everything from `0x00` to `0x1f`.

Actually `int 0x10` is kind of working now, at least on some PCs.  Basically, to "implement" it, `biefircate` tries to look for a legacy-style option ROM for a VGA device, and initialize that.  On PCs where this succeeds, you get real, non-emulated standard VGA modes. ☺

(I hope to also get `int 0x13` working, later in the future.  Right now I am looking at how to properly initialize all the option ROMs &mdash; in particular iPXE invokes `int 0x1a` &mdash; and how to do IRQs 0 and 1.)

> could biefircate eventually also be extended to function as a hardware-assisted hypervisor that could emulate some legacy hardware such as legacy VGA and Sound Blaster, while allowing direct pass-through access to other hardware?

Well, for now
  * I am trying to keep things real (i.e. no virtualization), and
  * I am focusing on getting stuff to work on machines that have _some_ hardware- and firmware-level compatibility with the IBM PC (e.g. there is a VGA device and a VGA ROM that can talk to it).

This is mainly to maintain my sanity. 😐&nbsp; But yes, I guess at some point it will be useful to think about virtualization.

> Great work, regardless!

Thank you!

**Comment by tkchia** [comment]
Hello @volkertb,

> access to graphics and disk routines in 64-bit UEFI?

By the way, according to the UEFI specification, most of the UEFI services are meant to be used only at bootloader time, and are not available once the bootloader "exits boot services".  (The expectation is that an OS kernel will take over and supply its own device drivers and everything.)  This is one unfortunate way in which UEFI differs from the legacy BIOS.

Thank you!

**Comment by tkchia** [comment]
(I am converting this GitHub issue to a GitHub discussion topic.  Thank you!)
